###
#   Database Settings
#   Currently the database in configured for In-Memory mode, this can be changed to DBMS or FILE based on requirements.
###
spring:
  datasource:
    url: jdbc:h2:mem:recruiting-api-db;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    platform: h2
    username: sa
    password:
    driverClassName: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
  jackson.serialization.write-dates-as-timestamps: false

server:
    contextPath: /api/v1